# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QtSimpleView3.ui'
#
# Created: Sat Mar 12 15:24:23 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(603, 553)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralWidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.groupBox = QtGui.QGroupBox(self.centralWidget)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.formLayout = QtGui.QFormLayout(self.groupBox)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.doubleSpinBox_xbuffer = QtGui.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_xbuffer.setMaximum(500.0)
        self.doubleSpinBox_xbuffer.setSingleStep(0.1)
        self.doubleSpinBox_xbuffer.setProperty(_fromUtf8("value"), 2.0)
        self.doubleSpinBox_xbuffer.setObjectName(_fromUtf8("doubleSpinBox_xbuffer"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.doubleSpinBox_xbuffer)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.doubleSpinBox_ybuffer = QtGui.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_ybuffer.setMaximum(500.0)
        self.doubleSpinBox_ybuffer.setSingleStep(0.1)
        self.doubleSpinBox_ybuffer.setProperty(_fromUtf8("value"), 1.5)
        self.doubleSpinBox_ybuffer.setObjectName(_fromUtf8("doubleSpinBox_ybuffer"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.doubleSpinBox_ybuffer)
        self.doubleSpinBox_randSpread = QtGui.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_randSpread.setMaximum(500.0)
        self.doubleSpinBox_randSpread.setSingleStep(0.1)
        self.doubleSpinBox_randSpread.setProperty(_fromUtf8("value"), 0.2)
        self.doubleSpinBox_randSpread.setObjectName(_fromUtf8("doubleSpinBox_randSpread"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.doubleSpinBox_randSpread)
        self.doubleSpinBox_thetaMult = QtGui.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_thetaMult.setSingleStep(0.1)
        self.doubleSpinBox_thetaMult.setProperty(_fromUtf8("value"), 0.75)
        self.doubleSpinBox_thetaMult.setObjectName(_fromUtf8("doubleSpinBox_thetaMult"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.doubleSpinBox_thetaMult)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_6)
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_7)
        self.doubleSpinBox_thetaPow = QtGui.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_thetaPow.setMaximum(93.99)
        self.doubleSpinBox_thetaPow.setSingleStep(0.1)
        self.doubleSpinBox_thetaPow.setProperty(_fromUtf8("value"), 0.67)
        self.doubleSpinBox_thetaPow.setObjectName(_fromUtf8("doubleSpinBox_thetaPow"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.doubleSpinBox_thetaPow)
        self.doubleSpinBox_rMult = QtGui.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_rMult.setSingleStep(0.1)
        self.doubleSpinBox_rMult.setProperty(_fromUtf8("value"), 2.0)
        self.doubleSpinBox_rMult.setObjectName(_fromUtf8("doubleSpinBox_rMult"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.doubleSpinBox_rMult)
        self.doubleSpinBox_rPow = QtGui.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_rPow.setSingleStep(0.1)
        self.doubleSpinBox_rPow.setProperty(_fromUtf8("value"), 0.5)
        self.doubleSpinBox_rPow.setObjectName(_fromUtf8("doubleSpinBox_rPow"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.doubleSpinBox_rPow)
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_8)
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_9)
        self.doubleSpinBox_dMult = QtGui.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_dMult.setMaximum(200.0)
        self.doubleSpinBox_dMult.setSingleStep(0.1)
        self.doubleSpinBox_dMult.setProperty(_fromUtf8("value"), 2.5)
        self.doubleSpinBox_dMult.setObjectName(_fromUtf8("doubleSpinBox_dMult"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.doubleSpinBox_dMult)
        self.doubleSpinBox_dPow = QtGui.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_dPow.setSingleStep(0.05)
        self.doubleSpinBox_dPow.setProperty(_fromUtf8("value"), 0.75)
        self.doubleSpinBox_dPow.setObjectName(_fromUtf8("doubleSpinBox_dPow"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.doubleSpinBox_dPow)
        self.label_10 = QtGui.QLabel(self.groupBox)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout.setWidget(10, QtGui.QFormLayout.LabelRole, self.label_10)
        self.comboBox_pathShape = QtGui.QComboBox(self.groupBox)
        self.comboBox_pathShape.setObjectName(_fromUtf8("comboBox_pathShape"))
        self.comboBox_pathShape.addItem(_fromUtf8(""))
        self.comboBox_pathShape.addItem(_fromUtf8(""))
        self.formLayout.setWidget(10, QtGui.QFormLayout.FieldRole, self.comboBox_pathShape)
        self.label_11 = QtGui.QLabel(self.groupBox)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout.setWidget(9, QtGui.QFormLayout.LabelRole, self.label_11)
        self.doubleSpinBox_wordSizePower = QtGui.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_wordSizePower.setMaximum(5.0)
        self.doubleSpinBox_wordSizePower.setSingleStep(0.1)
        self.doubleSpinBox_wordSizePower.setProperty(_fromUtf8("value"), 1.0)
        self.doubleSpinBox_wordSizePower.setObjectName(_fromUtf8("doubleSpinBox_wordSizePower"))
        self.formLayout.setWidget(9, QtGui.QFormLayout.FieldRole, self.doubleSpinBox_wordSizePower)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 603, 22))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menuBar)
        self.actionNew = QtGui.QAction(MainWindow)
        self.actionNew.setObjectName(_fromUtf8("actionNew"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Layout Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "x buffer", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "y buffer", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "rand spread", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "theta mult", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "theta pow", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "r mult", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "r pow", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "d mult", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "d pow", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Layout Shape", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_pathShape.setItemText(0, QtGui.QApplication.translate("MainWindow", "Circular", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_pathShape.setItemText(1, QtGui.QApplication.translate("MainWindow", "Square", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Word size power", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setText(QtGui.QApplication.translate("MainWindow", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))

