# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QtSimpleView3.ui'
#
# Created: Sun Mar 13 10:37:11 2011
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(603, 553)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtGui.QGridLayout(self.centralWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtGui.QGroupBox(self.centralWidget)
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtGui.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.doubleSpinBox_xbuffer = QtGui.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_xbuffer.setMaximum(500.0)
        self.doubleSpinBox_xbuffer.setSingleStep(0.1)
        self.doubleSpinBox_xbuffer.setProperty("value", 2.0)
        self.doubleSpinBox_xbuffer.setObjectName("doubleSpinBox_xbuffer")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.doubleSpinBox_xbuffer)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.doubleSpinBox_ybuffer = QtGui.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_ybuffer.setMaximum(500.0)
        self.doubleSpinBox_ybuffer.setSingleStep(0.1)
        self.doubleSpinBox_ybuffer.setProperty("value", 1.5)
        self.doubleSpinBox_ybuffer.setObjectName("doubleSpinBox_ybuffer")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.doubleSpinBox_ybuffer)
        self.doubleSpinBox_randSpread = QtGui.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_randSpread.setMaximum(500.0)
        self.doubleSpinBox_randSpread.setSingleStep(0.1)
        self.doubleSpinBox_randSpread.setProperty("value", 0.2)
        self.doubleSpinBox_randSpread.setObjectName("doubleSpinBox_randSpread")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.doubleSpinBox_randSpread)
        self.doubleSpinBox_thetaMult = QtGui.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_thetaMult.setSingleStep(0.1)
        self.doubleSpinBox_thetaMult.setProperty("value", 0.75)
        self.doubleSpinBox_thetaMult.setObjectName("doubleSpinBox_thetaMult")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.doubleSpinBox_thetaMult)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_6)
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_7)
        self.doubleSpinBox_thetaPow = QtGui.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_thetaPow.setMaximum(93.99)
        self.doubleSpinBox_thetaPow.setSingleStep(0.1)
        self.doubleSpinBox_thetaPow.setProperty("value", 0.67)
        self.doubleSpinBox_thetaPow.setObjectName("doubleSpinBox_thetaPow")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.doubleSpinBox_thetaPow)
        self.doubleSpinBox_rMult = QtGui.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_rMult.setSingleStep(0.1)
        self.doubleSpinBox_rMult.setProperty("value", 2.0)
        self.doubleSpinBox_rMult.setObjectName("doubleSpinBox_rMult")
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.doubleSpinBox_rMult)
        self.doubleSpinBox_rPow = QtGui.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_rPow.setSingleStep(0.1)
        self.doubleSpinBox_rPow.setProperty("value", 0.5)
        self.doubleSpinBox_rPow.setObjectName("doubleSpinBox_rPow")
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.doubleSpinBox_rPow)
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_8)
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_9)
        self.doubleSpinBox_dMult = QtGui.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_dMult.setMaximum(200.0)
        self.doubleSpinBox_dMult.setSingleStep(0.1)
        self.doubleSpinBox_dMult.setProperty("value", 2.5)
        self.doubleSpinBox_dMult.setObjectName("doubleSpinBox_dMult")
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.doubleSpinBox_dMult)
        self.doubleSpinBox_dPow = QtGui.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_dPow.setSingleStep(0.05)
        self.doubleSpinBox_dPow.setProperty("value", 0.75)
        self.doubleSpinBox_dPow.setObjectName("doubleSpinBox_dPow")
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.doubleSpinBox_dPow)
        self.label_10 = QtGui.QLabel(self.groupBox)
        self.label_10.setObjectName("label_10")
        self.formLayout.setWidget(10, QtGui.QFormLayout.LabelRole, self.label_10)
        self.comboBox_pathShape = QtGui.QComboBox(self.groupBox)
        self.comboBox_pathShape.setObjectName("comboBox_pathShape")
        self.comboBox_pathShape.addItem("")
        self.comboBox_pathShape.addItem("")
        self.formLayout.setWidget(10, QtGui.QFormLayout.FieldRole, self.comboBox_pathShape)
        self.label_11 = QtGui.QLabel(self.groupBox)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(9, QtGui.QFormLayout.LabelRole, self.label_11)
        self.doubleSpinBox_wordSizePower = QtGui.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_wordSizePower.setMaximum(5.0)
        self.doubleSpinBox_wordSizePower.setSingleStep(0.1)
        self.doubleSpinBox_wordSizePower.setProperty("value", 1.0)
        self.doubleSpinBox_wordSizePower.setObjectName("doubleSpinBox_wordSizePower")
        self.formLayout.setWidget(9, QtGui.QFormLayout.FieldRole, self.doubleSpinBox_wordSizePower)
        self.comboBox_orientation = QtGui.QComboBox(self.groupBox)
        self.comboBox_orientation.setObjectName("comboBox_orientation")
        self.comboBox_orientation.addItem("")
        self.comboBox_orientation.addItem("")
        self.comboBox_orientation.addItem("")
        self.comboBox_orientation.addItem("")
        self.comboBox_orientation.addItem("")
        self.formLayout.setWidget(11, QtGui.QFormLayout.FieldRole, self.comboBox_orientation)
        self.label_12 = QtGui.QLabel(self.groupBox)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(11, QtGui.QFormLayout.LabelRole, self.label_12)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 603, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menuBar)
        self.actionNew = QtGui.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Layout Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "x buffer", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "y buffer", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "rand spread", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "theta mult", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "theta pow", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "r mult", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "r pow", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "d mult", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "d pow", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "Layout Shape", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_pathShape.setItemText(0, QtGui.QApplication.translate("MainWindow", "Circular", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_pathShape.setItemText(1, QtGui.QApplication.translate("MainWindow", "Square", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "Word size power", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_orientation.setItemText(0, QtGui.QApplication.translate("MainWindow", "Horizontal", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_orientation.setItemText(1, QtGui.QApplication.translate("MainWindow", "Mostly horizontal", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_orientation.setItemText(2, QtGui.QApplication.translate("MainWindow", "Half and half", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_orientation.setItemText(3, QtGui.QApplication.translate("MainWindow", "Mostly vertical", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_orientation.setItemText(4, QtGui.QApplication.translate("MainWindow", "Vertical", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "Word Orientation", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setText(QtGui.QApplication.translate("MainWindow", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNew.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+N", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))

