try: paraview.simple
except: from paraview.simple import *

RenderView1 = CreateRenderView()
RenderView1.LightSpecularColor = [1.0, 1.0, 1.0]
RenderView1.UseLight = 1
RenderView1.CameraPosition = [7.16745062544204, 205.35120321764757, 149.7191301636953]
RenderView1.FillLightKFRatio = 3.0
RenderView1.FillLightAzimuth = -10.0
RenderView1.LODResolution = 50
RenderView1.KeyLightAzimuth = 10.0
RenderView1.LightIntensity = 1.0
RenderView1.CameraFocalPoint = [159.59425377845614, 159.56531116366355, 159.55820569395851]
RenderView1.CameraViewAngle = 30.0
RenderView1.CameraParallelScale = 277.650350851967
RenderView1.EyeAngle = 2.0
RenderView1.HeadLightKHRatio = 3.0
RenderView1.UseTriangleStrips = 0
RenderView1.StereoRender = 0
RenderView1.RenderInterruptsEnabled = 0
RenderView1.KeyLightIntensity = 0.75
RenderView1.BackLightAzimuth = 110.0
RenderView1.Background = [0.16470588235294117, 0.16078431372549021, 0.14509803921568629]
RenderView1.UseOffscreenRenderingForScreenshots = 0
RenderView1.CenterOfRotation = [159.59425377845764, 159.56531116366386, 159.55820569396019]
RenderView1.CameraParallelProjection = 0
RenderView1.CameraViewUp = [-0.11288880363840337, -0.55318746801617147, -0.82537248757330617]
RenderView1.HeadLightWarmth = 0.5
RenderView1.MaximumNumberOfPeels = 4
RenderView1.LightDiffuseColor = [1.0, 1.0, 1.0]
RenderView1.StereoType = 'Red-Blue'
RenderView1.DepthPeeling = 1
RenderView1.BackLightKBRatio = 3.5
RenderView1.UseImmediateMode = 1
RenderView1.LightAmbientColor = [1.0, 1.0, 1.0]
RenderView1.KeyLightElevation = 50.0
RenderView1.MaintainLuminance = 0
RenderView1.BackLightWarmth = 0.5
RenderView1.FillLightElevation = -75.0
RenderView1.FillLightWarmth = 0.40000000000000002
RenderView1.LightSwitch = 0
RenderView1.CameraClippingRange = [0.40895923110498755, 408.95923110498757]
RenderView1.BackLightElevation = 0.0
RenderView1.LODThreshold = 5.0
RenderView1.KeyLightWarmth = 0.59999999999999998

test1_fibers_xmf = XDMFReader2( guiName="test1_fibers.xmf", Grids=['Fibers', 'Fibers[1]', 'Fibers[2]', 'Fibers[3]', 'Fibers[4]', 'Fibers[5]', 'Fibers[6]', 'Fibers[7]', 'Fibers[8]', 'Fibers[9]', 'Fibers[10]'], CellArrays=[], PointArrays=['fibers_fibers_direction', 'fibers_fibers_property'], FileName='/Users/emonson/Data/MSI/LargeData/Fiber_070809/test1_fibers.xmf', Stride=[1, 1, 1], Sets=[] )

ExtractSelection1 = ExtractSelection( guiName="ExtractSelection1", Selection=[], ShowBounds=0, PreserveTopology=0 )

Glyph1 = Glyph( guiName="Glyph1", MaskPoints=0, Scalars=['POINTS', 'fibers_fibers_property'], RandomMode=0, Vectors=['POINTS', 'fibers_fibers_direction'], GlyphType="Line", MaximumNumberofPoints=5000, SetScaleFactor=1.0, ScaleMode='vector', Orient=1 )

Delaunay3D1 = Delaunay3D( guiName="Delaunay3D1", BoundingTriangulation=0, Alpha=0.0, Offset=2.5, Tolerance=0.001 )

ExtractSurface1 = ExtractSurface( guiName="ExtractSurface1", PieceInvariant=1 )

a1_fibers_fibers_property_PiecewiseFunction = CreatePiecewiseFunction( Points=[0.0, 0.0, 2.0, 1.0] )

a1_fibers_fibers_property_PVLookupTable = CreateLookupTable( Discretize=1, RGBPoints=[0.0, 0.23000000000000001, 0.29899999999999999, 0.754, 2.0, 0.80440985732814529, 0.0, 0.14811932555123217], UseLogScale=0, VectorComponent=0, NumberOfTableValues=256, ColorSpace='Diverging', VectorMode='Magnitude', HSVWrap=0, ScalarRangeInitialized=1.0, LockScalarRange=0 )

DataRepresentation7 = Show()
DataRepresentation7.CubeAxesZAxisVisibility = 1
DataRepresentation7.SelectionPointLabelColor = [1.0, 1.0, 1.0]
DataRepresentation7.SelectionPointFieldDataArrayName = ''
DataRepresentation7.SuppressLOD = 0
DataRepresentation7.CubeAxesXGridLines = 0
DataRepresentation7.CubeAxesYAxisTickVisibility = 1
DataRepresentation7.Position = [0.0, 0.0, 0.0]
DataRepresentation7.BackfaceRepresentation = 'Follow Frontface'
DataRepresentation7.SelectionOpacity = 1.0
DataRepresentation7.SelectionPointLabelShadow = 0
DataRepresentation7.CubeAxesYGridLines = 0
DataRepresentation7.Shading = 0
DataRepresentation7.Diffuse = 1.0
DataRepresentation7.Origin = [0.0, 0.0, 0.0]
DataRepresentation7.CubeAxesZTitle = 'Z-Axis'
DataRepresentation7.Specular = 0.10000000000000001
DataRepresentation7.SelectionVisibility = 1
DataRepresentation7.InterpolateScalarsBeforeMapping = 1
DataRepresentation7.CubeAxesZAxisTickVisibility = 1
DataRepresentation7.SelectionUseOutline = 0
DataRepresentation7.SelectionCellFieldDataArrayIndex = 0
DataRepresentation7.CubeAxesVisibility = 0
DataRepresentation7.Scale = [1.0, 1.0, 1.0]
DataRepresentation7.SelectionCellLabelJustification = 'Center'
DataRepresentation7.DiffuseColor = [1.0, 1.0, 1.0]
DataRepresentation7.SelectionCellLabelOpacity = 1.0
DataRepresentation7.Opacity = 0.50000000000000011
DataRepresentation7.LineWidth = 1.0
DataRepresentation7.SelectionPointSize = 2.0
DataRepresentation7.Material = ''
DataRepresentation7.Visibility = 1
DataRepresentation7.SelectionCellLabelFontSize = 24
DataRepresentation7.CubeAxesCornerOffset = 0.0
DataRepresentation7.SelectionPointLabelJustification = 'Center'
DataRepresentation7.Ambient = 0.0
DataRepresentation7.CubeAxesTickLocation = 'Inside'
DataRepresentation7.BackfaceDiffuseColor = [1.0, 1.0, 1.0]
DataRepresentation7.CubeAxesYAxisVisibility = 1
DataRepresentation7.SelectionPointLabelFontFamily = 'Arial'
DataRepresentation7.CubeAxesFlyMode = 'Closest Triad'
DataRepresentation7.CubeAxesYTitle = 'Y-Axis'
DataRepresentation7.SelectionPointFieldDataArrayIndex = 0
DataRepresentation7.ColorAttributeType = 'POINT_DATA'
DataRepresentation7.SpecularPower = 100.0
DataRepresentation7.Texture = []
DataRepresentation7.SelectionCellLabelShadow = 0
DataRepresentation7.AmbientColor = [1.0, 1.0, 1.0]
DataRepresentation7.MapScalars = 1
DataRepresentation7.PointSize = 5.0
DataRepresentation7.StaticMode = 0
DataRepresentation7.SelectionCellLabelColor = [0.0, 1.0, 0.0]
DataRepresentation7.EdgeColor = [0.0, 0.0, 0.50000762951094835]
DataRepresentation7.CubeAxesXAxisTickVisibility = 1
DataRepresentation7.SelectionCellLabelVisibility = 0
DataRepresentation7.CubeAxesColor = [1.0, 1.0, 1.0]
DataRepresentation7.Representation = 'Surface With Edges'
DataRepresentation7.CubeAxesXAxisMinorTickVisibility = 1
DataRepresentation7.Orientation = [0.0, 0.0, 0.0]
DataRepresentation7.UseLookupTableScalarRange = 0
DataRepresentation7.CubeAxesXTitle = 'X-Axis'
DataRepresentation7.CubeAxesInertia = 1
DataRepresentation7.BackfaceOpacity = 1.0
DataRepresentation7.SelectionCellFieldDataArrayName = ''
DataRepresentation7.SelectionColor = [1.0, 0.0, 1.0]
DataRepresentation7.SelectionPointLabelVisibility = 0
DataRepresentation7.SelectionPointLabelFontSize = 18
DataRepresentation7.BackfaceAmbientColor = [1.0, 1.0, 1.0]
DataRepresentation7.SelectionLineWidth = 2.0
DataRepresentation7.CubeAxesZAxisMinorTickVisibility = 1
DataRepresentation7.CubeAxesXAxisVisibility = 1
DataRepresentation7.Interpolation = 'Gouraud'
DataRepresentation7.SelectionCellLabelFontFamily = 'Arial'
DataRepresentation7.SelectionCellLabelItalic = 0
DataRepresentation7.CubeAxesYAxisMinorTickVisibility = 1
DataRepresentation7.CubeAxesZGridLines = 0
DataRepresentation7.SelectionPointLabelOpacity = 1.0
DataRepresentation7.Pickable = 1
DataRepresentation7.SelectionRepresentation = 'Wireframe'
DataRepresentation7.ClippingPlanes = []
DataRepresentation7.SelectionPointLabelBold = 0
DataRepresentation7.NumberOfSubPieces = 1
DataRepresentation7.ColorArrayName = 'fibers_fibers_property'
DataRepresentation7.SelectionPointLabelItalic = 0
DataRepresentation7.SpecularColor = [1.0, 1.0, 1.0]
DataRepresentation7.LookupTable = a1_fibers_fibers_property_PVLookupTable
DataRepresentation7.SelectionCellLabelBold = 0

SetActiveSource(Glyph1)
DataRepresentation3 = Show()
DataRepresentation3.CubeAxesZAxisVisibility = 1
DataRepresentation3.SelectionPointLabelColor = [1.0, 1.0, 1.0]
DataRepresentation3.SelectionPointFieldDataArrayName = ''
DataRepresentation3.SuppressLOD = 0
DataRepresentation3.CubeAxesXGridLines = 0
DataRepresentation3.CubeAxesYAxisTickVisibility = 1
DataRepresentation3.Position = [0.0, 0.0, 0.0]
DataRepresentation3.BackfaceRepresentation = 'Follow Frontface'
DataRepresentation3.SelectionOpacity = 1.0
DataRepresentation3.SelectionPointLabelShadow = 0
DataRepresentation3.CubeAxesYGridLines = 0
DataRepresentation3.Shading = 0
DataRepresentation3.Diffuse = 1.0
DataRepresentation3.Origin = [0.0, 0.0, 0.0]
DataRepresentation3.CubeAxesZTitle = 'Z-Axis'
DataRepresentation3.Specular = 0.10000000000000001
DataRepresentation3.SelectionVisibility = 1
DataRepresentation3.InterpolateScalarsBeforeMapping = 1
DataRepresentation3.CubeAxesZAxisTickVisibility = 1
DataRepresentation3.SelectionUseOutline = 0
DataRepresentation3.SelectionCellFieldDataArrayIndex = 0
DataRepresentation3.CubeAxesVisibility = 0
DataRepresentation3.Scale = [1.0, 1.0, 1.0]
DataRepresentation3.SelectionCellLabelJustification = 'Center'
DataRepresentation3.DiffuseColor = [1.0, 1.0, 1.0]
DataRepresentation3.SelectionCellLabelOpacity = 1.0
DataRepresentation3.Opacity = 1.0
DataRepresentation3.LineWidth = 1.0
DataRepresentation3.SelectionPointSize = 2.0
DataRepresentation3.Material = ''
DataRepresentation3.Visibility = 1
DataRepresentation3.SelectionCellLabelFontSize = 24
DataRepresentation3.CubeAxesCornerOffset = 0.0
DataRepresentation3.SelectionPointLabelJustification = 'Center'
DataRepresentation3.Ambient = 0.0
DataRepresentation3.CubeAxesTickLocation = 'Inside'
DataRepresentation3.BackfaceDiffuseColor = [1.0, 1.0, 1.0]
DataRepresentation3.CubeAxesYAxisVisibility = 1
DataRepresentation3.SelectionPointLabelFontFamily = 'Arial'
DataRepresentation3.CubeAxesFlyMode = 'Closest Triad'
DataRepresentation3.CubeAxesYTitle = 'Y-Axis'
DataRepresentation3.SelectionPointFieldDataArrayIndex = 0
DataRepresentation3.ColorAttributeType = 'POINT_DATA'
DataRepresentation3.SpecularPower = 100.0
DataRepresentation3.Texture = []
DataRepresentation3.SelectionCellLabelShadow = 0
DataRepresentation3.AmbientColor = [1.0, 1.0, 1.0]
DataRepresentation3.MapScalars = 1
DataRepresentation3.PointSize = 5.0
DataRepresentation3.StaticMode = 0
DataRepresentation3.SelectionCellLabelColor = [0.0, 1.0, 0.0]
DataRepresentation3.EdgeColor = [0.0, 0.0, 0.50000762951094835]
DataRepresentation3.CubeAxesXAxisTickVisibility = 1
DataRepresentation3.SelectionCellLabelVisibility = 0
DataRepresentation3.CubeAxesColor = [1.0, 1.0, 1.0]
DataRepresentation3.Representation = 'Surface'
DataRepresentation3.CubeAxesXAxisMinorTickVisibility = 1
DataRepresentation3.Orientation = [0.0, 0.0, 0.0]
DataRepresentation3.UseLookupTableScalarRange = 0
DataRepresentation3.CubeAxesXTitle = 'X-Axis'
DataRepresentation3.CubeAxesInertia = 1
DataRepresentation3.BackfaceOpacity = 1.0
DataRepresentation3.SelectionCellFieldDataArrayName = ''
DataRepresentation3.SelectionColor = [1.0, 0.0, 1.0]
DataRepresentation3.SelectionPointLabelVisibility = 0
DataRepresentation3.SelectionPointLabelFontSize = 18
DataRepresentation3.BackfaceAmbientColor = [1.0, 1.0, 1.0]
DataRepresentation3.SelectionLineWidth = 2.0
DataRepresentation3.CubeAxesZAxisMinorTickVisibility = 1
DataRepresentation3.CubeAxesXAxisVisibility = 1
DataRepresentation3.Interpolation = 'Gouraud'
DataRepresentation3.SelectionCellLabelFontFamily = 'Arial'
DataRepresentation3.SelectionCellLabelItalic = 0
DataRepresentation3.CubeAxesYAxisMinorTickVisibility = 1
DataRepresentation3.CubeAxesZGridLines = 0
DataRepresentation3.SelectionPointLabelOpacity = 1.0
DataRepresentation3.Pickable = 1
DataRepresentation3.SelectionRepresentation = 'Wireframe'
DataRepresentation3.ClippingPlanes = []
DataRepresentation3.SelectionPointLabelBold = 0
DataRepresentation3.NumberOfSubPieces = 1
DataRepresentation3.ColorArrayName = 'fibers_fibers_property'
DataRepresentation3.SelectionPointLabelItalic = 0
DataRepresentation3.SpecularColor = [1.0, 1.0, 1.0]
DataRepresentation3.LookupTable = a1_fibers_fibers_property_PVLookupTable
DataRepresentation3.SelectionCellLabelBold = 0

SetActiveSource(Delaunay3D1)
DataRepresentation6 = Show()
DataRepresentation6.CubeAxesZAxisVisibility = 1
DataRepresentation6.SelectionPointLabelColor = [1.0, 1.0, 1.0]
DataRepresentation6.SelectionPointFieldDataArrayName = ''
DataRepresentation6.SuppressLOD = 0
DataRepresentation6.CubeAxesXGridLines = 0
DataRepresentation6.CubeAxesYAxisTickVisibility = 1
DataRepresentation6.Position = [0.0, 0.0, 0.0]
DataRepresentation6.BackfaceRepresentation = 'Follow Frontface'
DataRepresentation6.SelectionOpacity = 1.0
DataRepresentation6.SelectionPointLabelShadow = 0
DataRepresentation6.CubeAxesYGridLines = 0
DataRepresentation6.Shading = 0
DataRepresentation6.Diffuse = 1.0
DataRepresentation6.Origin = [0.0, 0.0, 0.0]
DataRepresentation6.CubeAxesZTitle = 'Z-Axis'
DataRepresentation6.Specular = 0.10000000000000001
DataRepresentation6.SelectionVisibility = 1
DataRepresentation6.InterpolateScalarsBeforeMapping = 1
DataRepresentation6.CubeAxesZAxisTickVisibility = 1
DataRepresentation6.SelectionUseOutline = 0
DataRepresentation6.SelectionCellFieldDataArrayIndex = 0
DataRepresentation6.CubeAxesVisibility = 0
DataRepresentation6.Scale = [1.0, 1.0, 1.0]
DataRepresentation6.SelectionCellLabelJustification = 'Center'
DataRepresentation6.DiffuseColor = [1.0, 1.0, 1.0]
DataRepresentation6.SelectionCellLabelOpacity = 1.0
DataRepresentation6.CubeAxesInertia = 1
DataRepresentation6.Opacity = 0.50000000000000011
DataRepresentation6.LineWidth = 1.0
DataRepresentation6.SelectionPointSize = 2.0
DataRepresentation6.Material = ''
DataRepresentation6.Visibility = 0
DataRepresentation6.SelectionCellLabelFontSize = 24
DataRepresentation6.CubeAxesCornerOffset = 0.0
DataRepresentation6.SelectionPointLabelJustification = 'Center'
DataRepresentation6.Ambient = 0.0
DataRepresentation6.SelectedMapperIndex = 'Projected tetra'
DataRepresentation6.CubeAxesTickLocation = 'Inside'
DataRepresentation6.BackfaceDiffuseColor = [1.0, 1.0, 1.0]
DataRepresentation6.CubeAxesYAxisVisibility = 1
DataRepresentation6.SelectionPointLabelFontFamily = 'Arial'
DataRepresentation6.CubeAxesFlyMode = 'Closest Triad'
DataRepresentation6.CubeAxesYTitle = 'Y-Axis'
DataRepresentation6.SelectionPointFieldDataArrayIndex = 0
DataRepresentation6.ColorAttributeType = 'POINT_DATA'
DataRepresentation6.SpecularPower = 100.0
DataRepresentation6.Texture = []
DataRepresentation6.SelectionCellLabelShadow = 0
DataRepresentation6.AmbientColor = [1.0, 1.0, 1.0]
DataRepresentation6.MapScalars = 1
DataRepresentation6.PointSize = 5.0
DataRepresentation6.StaticMode = 0
DataRepresentation6.SelectionCellLabelColor = [0.0, 1.0, 0.0]
DataRepresentation6.EdgeColor = [0.0, 0.0, 0.50000762951094835]
DataRepresentation6.CubeAxesXAxisTickVisibility = 1
DataRepresentation6.SelectionCellLabelVisibility = 0
DataRepresentation6.CubeAxesColor = [1.0, 1.0, 1.0]
DataRepresentation6.Representation = 'Surface With Edges'
DataRepresentation6.CubeAxesXAxisMinorTickVisibility = 1
DataRepresentation6.Orientation = [0.0, 0.0, 0.0]
DataRepresentation6.UseLookupTableScalarRange = 0
DataRepresentation6.CubeAxesXTitle = 'X-Axis'
DataRepresentation6.ScalarOpacityUnitDistance = 5.3730902760545147
DataRepresentation6.BackfaceOpacity = 1.0
DataRepresentation6.SelectionCellFieldDataArrayName = ''
DataRepresentation6.SelectionColor = [1.0, 0.0, 1.0]
DataRepresentation6.SelectionPointLabelVisibility = 0
DataRepresentation6.SelectionPointLabelFontSize = 18
DataRepresentation6.BackfaceAmbientColor = [1.0, 1.0, 1.0]
DataRepresentation6.ScalarOpacityFunction = a1_fibers_fibers_property_PiecewiseFunction
DataRepresentation6.SelectionLineWidth = 2.0
DataRepresentation6.CubeAxesZAxisMinorTickVisibility = 1
DataRepresentation6.CubeAxesXAxisVisibility = 1
DataRepresentation6.Interpolation = 'Gouraud'
DataRepresentation6.SelectionCellLabelFontFamily = 'Arial'
DataRepresentation6.SelectionCellLabelItalic = 0
DataRepresentation6.CubeAxesYAxisMinorTickVisibility = 1
DataRepresentation6.CubeAxesZGridLines = 0
DataRepresentation6.ExtractedBlockIndex = 0
DataRepresentation6.SelectionPointLabelOpacity = 1.0
DataRepresentation6.Pickable = 1
DataRepresentation6.SelectionRepresentation = 'Wireframe'
DataRepresentation6.ClippingPlanes = []
DataRepresentation6.SelectionPointLabelBold = 0
DataRepresentation6.NumberOfSubPieces = 1
DataRepresentation6.ColorArrayName = 'fibers_fibers_property'
DataRepresentation6.SelectionPointLabelItalic = 0
DataRepresentation6.SpecularColor = [1.0, 1.0, 1.0]
DataRepresentation6.LookupTable = a1_fibers_fibers_property_PVLookupTable
DataRepresentation6.SelectionCellLabelBold = 0

SetActiveSource(test1_fibers_xmf)
DataRepresentation1 = Show()
DataRepresentation1.CubeAxesZAxisVisibility = 1
DataRepresentation1.SelectionPointLabelColor = [1.0, 1.0, 1.0]
DataRepresentation1.SelectionPointFieldDataArrayName = 'vtkOriginalPointIds'
DataRepresentation1.SuppressLOD = 0
DataRepresentation1.CubeAxesXGridLines = 0
DataRepresentation1.CubeAxesYAxisTickVisibility = 1
DataRepresentation1.Position = [0.0, 0.0, 0.0]
DataRepresentation1.BackfaceRepresentation = 'Follow Frontface'
DataRepresentation1.SelectionOpacity = 1.0
DataRepresentation1.SelectionPointLabelShadow = 0
DataRepresentation1.CubeAxesYGridLines = 0
DataRepresentation1.Shading = 0
DataRepresentation1.Diffuse = 1.0
DataRepresentation1.Origin = [0.0, 0.0, 0.0]
DataRepresentation1.CubeAxesZTitle = 'Z-Axis'
DataRepresentation1.Specular = 0.10000000000000001
DataRepresentation1.SelectionVisibility = 1
DataRepresentation1.InterpolateScalarsBeforeMapping = 1
DataRepresentation1.CubeAxesZAxisTickVisibility = 1
DataRepresentation1.SelectionUseOutline = 0
DataRepresentation1.SelectionCellFieldDataArrayIndex = 0
DataRepresentation1.CubeAxesVisibility = 0
DataRepresentation1.Scale = [1.0, 1.0, 1.0]
DataRepresentation1.SelectionCellLabelJustification = 'Center'
DataRepresentation1.DiffuseColor = [1.0, 1.0, 1.0]
DataRepresentation1.SelectionCellLabelOpacity = 1.0
DataRepresentation1.CubeAxesInertia = 1
DataRepresentation1.Opacity = 1.0
DataRepresentation1.LineWidth = 1.0
DataRepresentation1.SelectionPointSize = 2.0
DataRepresentation1.Material = ''
DataRepresentation1.Visibility = 1
DataRepresentation1.SelectionCellLabelFontSize = 24
DataRepresentation1.CubeAxesCornerOffset = 0.0
DataRepresentation1.SelectionPointLabelJustification = 'Center'
DataRepresentation1.Ambient = 0.0
DataRepresentation1.SelectedMapperIndex = 'Projected tetra'
DataRepresentation1.CubeAxesTickLocation = 'Inside'
DataRepresentation1.BackfaceDiffuseColor = [1.0, 1.0, 1.0]
DataRepresentation1.CubeAxesYAxisVisibility = 1
DataRepresentation1.SelectionPointLabelFontFamily = 'Arial'
DataRepresentation1.CubeAxesFlyMode = 'Closest Triad'
DataRepresentation1.CubeAxesYTitle = 'Y-Axis'
DataRepresentation1.SelectionPointFieldDataArrayIndex = 0
DataRepresentation1.ColorAttributeType = 'POINT_DATA'
DataRepresentation1.SpecularPower = 100.0
DataRepresentation1.Texture = []
DataRepresentation1.SelectionCellLabelShadow = 0
DataRepresentation1.AmbientColor = [1.0, 1.0, 1.0]
DataRepresentation1.MapScalars = 1
DataRepresentation1.PointSize = 3.0
DataRepresentation1.StaticMode = 0
DataRepresentation1.SelectionCellLabelColor = [0.0, 1.0, 0.0]
DataRepresentation1.EdgeColor = [0.0, 0.0, 0.50000762951094835]
DataRepresentation1.CubeAxesXAxisTickVisibility = 1
DataRepresentation1.SelectionCellLabelVisibility = 0
DataRepresentation1.CubeAxesColor = [1.0, 1.0, 1.0]
DataRepresentation1.Representation = 'Surface'
DataRepresentation1.CubeAxesXAxisMinorTickVisibility = 1
DataRepresentation1.Orientation = [0.0, 0.0, 0.0]
DataRepresentation1.UseLookupTableScalarRange = 0
DataRepresentation1.CubeAxesXTitle = 'X-Axis'
DataRepresentation1.ScalarOpacityUnitDistance = 554.00550615030522
DataRepresentation1.BackfaceOpacity = 1.0
DataRepresentation1.SelectionCellFieldDataArrayName = 'vtkOriginalCellIds'
DataRepresentation1.SelectionColor = [1.0, 0.0, 1.0]
DataRepresentation1.SelectionPointLabelVisibility = 0
DataRepresentation1.SelectionPointLabelFontSize = 18
DataRepresentation1.BackfaceAmbientColor = [1.0, 1.0, 1.0]
DataRepresentation1.ScalarOpacityFunction = a1_fibers_fibers_property_PiecewiseFunction
DataRepresentation1.SelectionLineWidth = 2.0
DataRepresentation1.CubeAxesZAxisMinorTickVisibility = 1
DataRepresentation1.CubeAxesXAxisVisibility = 1
DataRepresentation1.Interpolation = 'Gouraud'
DataRepresentation1.SelectionCellLabelFontFamily = 'Arial'
DataRepresentation1.SelectionCellLabelItalic = 0
DataRepresentation1.CubeAxesYAxisMinorTickVisibility = 1
DataRepresentation1.CubeAxesZGridLines = 0
DataRepresentation1.ExtractedBlockIndex = 0
DataRepresentation1.SelectionPointLabelOpacity = 1.0
DataRepresentation1.Pickable = 1
DataRepresentation1.SelectionRepresentation = 'Wireframe'
DataRepresentation1.ClippingPlanes = []
DataRepresentation1.SelectionPointLabelBold = 0
DataRepresentation1.NumberOfSubPieces = 1
DataRepresentation1.ColorArrayName = 'fibers_fibers_property'
DataRepresentation1.SelectionPointLabelItalic = 0
DataRepresentation1.SpecularColor = [1.0, 1.0, 1.0]
DataRepresentation1.LookupTable = a1_fibers_fibers_property_PVLookupTable
DataRepresentation1.SelectionCellLabelBold = 0

SetActiveSource(ExtractSelection1)
DataRepresentation2 = Show()
DataRepresentation2.CubeAxesZAxisVisibility = 1
DataRepresentation2.SelectionPointLabelColor = [1.0, 1.0, 1.0]
DataRepresentation2.SelectionPointFieldDataArrayName = ''
DataRepresentation2.SuppressLOD = 0
DataRepresentation2.CubeAxesXGridLines = 0
DataRepresentation2.CubeAxesYAxisTickVisibility = 1
DataRepresentation2.Position = [0.0, 0.0, 0.0]
DataRepresentation2.BackfaceRepresentation = 'Follow Frontface'
DataRepresentation2.SelectionOpacity = 1.0
DataRepresentation2.SelectionPointLabelShadow = 0
DataRepresentation2.CubeAxesYGridLines = 0
DataRepresentation2.Shading = 0
DataRepresentation2.Diffuse = 1.0
DataRepresentation2.Origin = [0.0, 0.0, 0.0]
DataRepresentation2.CubeAxesZTitle = 'Z-Axis'
DataRepresentation2.Specular = 0.10000000000000001
DataRepresentation2.SelectionVisibility = 1
DataRepresentation2.InterpolateScalarsBeforeMapping = 1
DataRepresentation2.CubeAxesZAxisTickVisibility = 1
DataRepresentation2.SelectionUseOutline = 0
DataRepresentation2.SelectionCellFieldDataArrayIndex = 0
DataRepresentation2.CubeAxesVisibility = 0
DataRepresentation2.Scale = [1.0, 1.0, 1.0]
DataRepresentation2.SelectionCellLabelJustification = 'Center'
DataRepresentation2.DiffuseColor = [1.0, 1.0, 1.0]
DataRepresentation2.SelectionCellLabelOpacity = 1.0
DataRepresentation2.CubeAxesInertia = 1
DataRepresentation2.Opacity = 1.0
DataRepresentation2.LineWidth = 1.0
DataRepresentation2.SelectionPointSize = 2.0
DataRepresentation2.Material = ''
DataRepresentation2.Visibility = 1
DataRepresentation2.SelectionCellLabelFontSize = 24
DataRepresentation2.CubeAxesCornerOffset = 0.0
DataRepresentation2.SelectionPointLabelJustification = 'Center'
DataRepresentation2.Ambient = 0.0
DataRepresentation2.SelectedMapperIndex = 'Projected tetra'
DataRepresentation2.CubeAxesTickLocation = 'Inside'
DataRepresentation2.BackfaceDiffuseColor = [1.0, 1.0, 1.0]
DataRepresentation2.CubeAxesYAxisVisibility = 1
DataRepresentation2.SelectionPointLabelFontFamily = 'Arial'
DataRepresentation2.CubeAxesFlyMode = 'Closest Triad'
DataRepresentation2.CubeAxesYTitle = 'Y-Axis'
DataRepresentation2.SelectionPointFieldDataArrayIndex = 0
DataRepresentation2.ColorAttributeType = 'POINT_DATA'
DataRepresentation2.SpecularPower = 100.0
DataRepresentation2.Texture = []
DataRepresentation2.SelectionCellLabelShadow = 0
DataRepresentation2.AmbientColor = [1.0, 1.0, 1.0]
DataRepresentation2.MapScalars = 1
DataRepresentation2.PointSize = 5.0
DataRepresentation2.StaticMode = 0
DataRepresentation2.SelectionCellLabelColor = [0.0, 1.0, 0.0]
DataRepresentation2.EdgeColor = [0.0, 0.0, 0.50000762951094835]
DataRepresentation2.CubeAxesXAxisTickVisibility = 1
DataRepresentation2.SelectionCellLabelVisibility = 0
DataRepresentation2.CubeAxesColor = [1.0, 1.0, 1.0]
DataRepresentation2.Representation = 'Surface'
DataRepresentation2.CubeAxesXAxisMinorTickVisibility = 1
DataRepresentation2.Orientation = [0.0, 0.0, 0.0]
DataRepresentation2.UseLookupTableScalarRange = 0
DataRepresentation2.CubeAxesXTitle = 'X-Axis'
DataRepresentation2.ScalarOpacityUnitDistance = 0.0
DataRepresentation2.BackfaceOpacity = 1.0
DataRepresentation2.SelectionCellFieldDataArrayName = ''
DataRepresentation2.SelectionColor = [1.0, 0.0, 1.0]
DataRepresentation2.SelectionPointLabelVisibility = 0
DataRepresentation2.SelectionPointLabelFontSize = 18
DataRepresentation2.BackfaceAmbientColor = [1.0, 1.0, 1.0]
DataRepresentation2.ScalarOpacityFunction = a1_fibers_fibers_property_PiecewiseFunction
DataRepresentation2.SelectionLineWidth = 2.0
DataRepresentation2.CubeAxesZAxisMinorTickVisibility = 1
DataRepresentation2.CubeAxesXAxisVisibility = 1
DataRepresentation2.Interpolation = 'Gouraud'
DataRepresentation2.SelectionCellLabelFontFamily = 'Arial'
DataRepresentation2.SelectionCellLabelItalic = 0
DataRepresentation2.CubeAxesYAxisMinorTickVisibility = 1
DataRepresentation2.CubeAxesZGridLines = 0
DataRepresentation2.ExtractedBlockIndex = 0
DataRepresentation2.SelectionPointLabelOpacity = 1.0
DataRepresentation2.Pickable = 1
DataRepresentation2.SelectionRepresentation = 'Wireframe'
DataRepresentation2.ClippingPlanes = []
DataRepresentation2.SelectionPointLabelBold = 0
DataRepresentation2.NumberOfSubPieces = 1
DataRepresentation2.ColorArrayName = 'fibers_fibers_property'
DataRepresentation2.SelectionPointLabelItalic = 0
DataRepresentation2.SpecularColor = [1.0, 1.0, 1.0]
DataRepresentation2.LookupTable = a1_fibers_fibers_property_PVLookupTable
DataRepresentation2.SelectionCellLabelBold = 0

Glyph1.GlyphType.Point1 = [0.0, 0.0, 0.0]
Glyph1.GlyphType.Point2 = [1.0, 0.0, 0.0]
Glyph1.GlyphType.Resolution = 6

Render()
